// Auto-generated by scripts/convert-lms-samples.ts. Do not hand-edit.
export interface LmsSampleEntry {
  slug: string;
  sourcePath: string;
  format: "word-blocks" | "python";
  targets: string[];
}

export const lmsSamples: LmsSampleEntry[] = [
  {
    "slug": "caterpillar",
    "sourcePath": "Caterpillar/Caterpillar.lms",
    "format": "word-blocks",
    "targets": [
      "caterpillar"
    ]
  },
  {
    "slug": "gelo-1",
    "sourcePath": "Gelo 1.lms",
    "format": "word-blocks",
    "targets": [
      "gelo-1"
    ]
  },
  {
    "slug": "monowheel",
    "sourcePath": "Monowheel/Monowheel.lms",
    "format": "word-blocks",
    "targets": [
      "monowheel"
    ]
  },
  {
    "slug": "remote-control-batman-bike",
    "sourcePath": "Remote Control Batman Bike.lms",
    "format": "word-blocks",
    "targets": [
      "remote-control-batman-bike"
    ]
  },
  {
    "slug": "tars-blocks-v1",
    "sourcePath": "Tars-program-files-21-01-19/Tars blocks v1.lms",
    "format": "word-blocks",
    "targets": [
      "tars-blocks-v1"
    ]
  },
  {
    "slug": "tars-blocks-v2",
    "sourcePath": "Tars-program-files-21-01-19/Tars blocks v2.lms",
    "format": "word-blocks",
    "targets": [
      "tars-blocks-v2"
    ]
  },
  {
    "slug": "tars-blocks-v3",
    "sourcePath": "Tars-program-files-21-01-19/Tars blocks v3.lms",
    "format": "word-blocks",
    "targets": [
      "tars-blocks-v3"
    ]
  },
  {
    "slug": "tars-python-v1",
    "sourcePath": "Tars-program-files-21-01-19/Tars python v1.lms",
    "format": "python",
    "targets": [
      "tars-python-v1"
    ]
  },
  {
    "slug": "tars-python-v3-2",
    "sourcePath": "Tars-program-files-21-01-19/Tars python v3 2.lms",
    "format": "python",
    "targets": [
      "tars-python-v3-2"
    ]
  },
  {
    "slug": "tars-python-v3",
    "sourcePath": "Tars-program-files-21-01-19/Tars python v3.lms",
    "format": "python",
    "targets": [
      "tars-python-v3"
    ]
  },
  {
    "slug": "walking-robot",
    "sourcePath": "Walking Robot.lms",
    "format": "word-blocks",
    "targets": [
      "walking-robot"
    ]
  }
];
