/**
 * One-off batch conversion: find every .lms file checked into this repo
 * (student robot programs made in the LEGO Robot Inventor app) and convert
 * each into TypeScript under src/data/lms-samples/, using the library in
 * src/lib/lms/.
 *
 * Run with: npx tsx scripts/convert-lms-samples.ts
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { join, relative, basename, extname } from "node:path";
import { convertLmsFile } from "../src/lib/lms/convertLmsFile";

const REPO_ROOT = join(import.meta.dirname, "..");
const OUT_DIR = join(REPO_ROOT, "src", "data", "lms-samples");
const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "src", "backend"]);

function findLmsFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      if (!SKIP_DIRS.has(entry)) findLmsFiles(full, out);
    } else if (extname(entry).toLowerCase() === ".lms") {
      out.push(full);
    }
  }
  return out;
}

function slugify(name: string): string {
  return name
    .replace(/\.lms$/i, "")
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

async function main() {
  const files = findLmsFiles(REPO_ROOT);
  mkdirSync(OUT_DIR, { recursive: true });

  const indexEntries: { slug: string; sourcePath: string; format: string; targets: string[] }[] = [];

  for (const filePath of files) {
    const projectName = basename(filePath, extname(filePath));
    const slug = slugify(basename(filePath));
    const sourcePath = relative(REPO_ROOT, filePath);
    console.log(`Converting ${sourcePath} ...`);

    try {
      const data = readFileSync(filePath);
      const result = await convertLmsFile(data, projectName);

      if (result.format === "word-blocks") {
        const targetNames: string[] = [];
        result.targets.forEach((target, i) => {
          const targetSlug = result.targets.length > 1 ? `${slug}-${slugify(target.name) || i}` : slug;
          const outPath = join(OUT_DIR, `${targetSlug}.ts`);
          writeFileSync(outPath, target.code);
          targetNames.push(targetSlug);
          console.log(`  -> src/data/lms-samples/${targetSlug}.ts (target "${target.name}")`);
        });
        indexEntries.push({ slug, sourcePath, format: result.format, targets: targetNames });
      } else {
        const outPath = join(OUT_DIR, `${slug}.ts`);
        writeFileSync(outPath, result.code);
        console.log(`  -> src/data/lms-samples/${slug}.ts`);
        indexEntries.push({ slug, sourcePath, format: result.format, targets: [slug] });
      }
    } catch (err) {
      console.error(`  FAILED: ${(err as Error).message}`);
    }
  }

  const indexLines = [
    `// Auto-generated by scripts/convert-lms-samples.ts. Do not hand-edit.`,
    `export interface LmsSampleEntry {`,
    `  slug: string;`,
    `  sourcePath: string;`,
    `  format: "word-blocks" | "python";`,
    `  targets: string[];`,
    `}`,
    ``,
    `export const lmsSamples: LmsSampleEntry[] = ${JSON.stringify(indexEntries, null, 2)};`,
    ``,
  ];
  writeFileSync(join(OUT_DIR, "index.ts"), indexLines.join("\n"));
  console.log(`\nWrote src/data/lms-samples/index.ts (${indexEntries.length} projects).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
